-- =============================================================================
-- 154_rent_ledger_one_time_charges.sql
-- Apply to staging first. Do NOT apply to production until approved.
--
-- Adds one-time lease charges on public.rent_ledger:
--   - charge_type text NOT NULL DEFAULT 'rent'  ('rent' | 'one_time')
--   - description text NULL  -- FLAG: beyond charge_type; label for one-time rows
--
-- Backfill: all existing rows → charge_type = 'rent'.
-- Safe to re-run (idempotent).
-- =============================================================================

BEGIN;

ALTER TABLE public.rent_ledger
  ADD COLUMN IF NOT EXISTS charge_type text,
  ADD COLUMN IF NOT EXISTS description text;

UPDATE public.rent_ledger
SET charge_type = 'rent'
WHERE charge_type IS NULL;

ALTER TABLE public.rent_ledger
  ALTER COLUMN charge_type SET DEFAULT 'rent';

ALTER TABLE public.rent_ledger
  ALTER COLUMN charge_type SET NOT NULL;

ALTER TABLE public.rent_ledger
  DROP CONSTRAINT IF EXISTS rent_ledger_charge_type_check;

ALTER TABLE public.rent_ledger
  ADD CONSTRAINT rent_ledger_charge_type_check
  CHECK (charge_type IN ('rent', 'one_time'));

-- One-time rows must carry a non-empty description; rent rows may leave it null.
ALTER TABLE public.rent_ledger
  DROP CONSTRAINT IF EXISTS rent_ledger_one_time_description_check;

ALTER TABLE public.rent_ledger
  ADD CONSTRAINT rent_ledger_one_time_description_check
  CHECK (
    charge_type <> 'one_time'
    OR (description IS NOT NULL AND length(btrim(description)) > 0)
  );

CREATE INDEX IF NOT EXISTS idx_rent_ledger_lease_charge_type
  ON public.rent_ledger (tenant_id, lease_id, charge_type);

COMMENT ON COLUMN public.rent_ledger.charge_type IS
  'rent = monthly rent period row; one_time = ad-hoc lease charge (not generated by rent cron).';

COMMENT ON COLUMN public.rent_ledger.description IS
  'FLAG: schema beyond charge_type. Human label for one_time charges (required). Null for rent rows.';

NOTIFY pgrst, 'reload schema';

COMMIT;
