"use client";

import { useMemo, useState } from "react";
import { inputClassName } from "../employees/employee-record-utils";
import { getStripedRowClassName } from "../finance/register-row-actions";
import ScrollableTable, {
  scrollableTableBodyClassName,
  scrollableTableClassName,
  scrollableTableHeadClassName,
  scrollableTableThClassName,
} from "../scrollable-table";
import type { RosterHistoryRecord } from "./duty-roster-utils";

type RosterHistoryEmployee = {
  employee_id: string;
  staff_id: string;
  full_name: string;
};

type RosterHistoryProps = {
  initialHistory: RosterHistoryRecord[];
  employees: RosterHistoryEmployee[];
  fetchError: string | null;
};

export default function RosterHistory({
  initialHistory,
  employees,
  fetchError,
}: RosterHistoryProps) {
  const [rotationFilter, setRotationFilter] = useState("");
  const [employeeFilter, setEmployeeFilter] = useState("");

  const employeeNameById = useMemo(() => {
    return new Map(
      employees.map((employee) => [employee.employee_id, employee.full_name]),
    );
  }, [employees]);

  const rotationOptions = useMemo(() => {
    const values = new Set<number>();
    for (const row of initialHistory) {
      if (row.rotation_number != null) {
        values.add(row.rotation_number);
      }
    }
    return [...values].sort((left, right) => right - left);
  }, [initialHistory]);

  const filteredHistory = useMemo(() => {
    return initialHistory.filter((row) => {
      if (
        rotationFilter &&
        String(row.rotation_number ?? "") !== rotationFilter
      ) {
        return false;
      }

      if (employeeFilter && row.employee_id !== employeeFilter) {
        return false;
      }

      return true;
    });
  }, [employeeFilter, initialHistory, rotationFilter]);

  if (fetchError) {
    return (
      <div className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
        {fetchError}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <p className="text-sm text-slate-600">
        Permanent audit trail of roster assignment changes. Records are
        append-only and cannot be edited or deleted.
      </p>

      <div className="grid gap-4 md:grid-cols-2">
        <div>
          <label className="mb-1 block text-sm font-medium text-slate-700">
            Filter by Rotation
          </label>
          <select
            value={rotationFilter}
            onChange={(event) => setRotationFilter(event.target.value)}
            className={inputClassName}
          >
            <option value="">All rotations</option>
            {rotationOptions.map((rotation) => (
              <option key={rotation} value={String(rotation)}>
                Rotation {rotation}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="mb-1 block text-sm font-medium text-slate-700">
            Filter by Employee
          </label>
          <select
            value={employeeFilter}
            onChange={(event) => setEmployeeFilter(event.target.value)}
            className={inputClassName}
          >
            <option value="">All employees</option>
            {employees.map((employee) => (
              <option key={employee.employee_id} value={employee.employee_id}>
                {employee.staff_id} — {employee.full_name}
              </option>
            ))}
          </select>
        </div>
      </div>

      <ScrollableTable>
        <table className={scrollableTableClassName}>
          <thead className={scrollableTableHeadClassName}>
            <tr>
              <th className={scrollableTableThClassName}>Roster #</th>
              <th className={scrollableTableThClassName}>Rotation</th>
              <th className={scrollableTableThClassName}>Effective</th>
              <th className={scrollableTableThClassName}>End</th>
              <th className={scrollableTableThClassName}>Employee</th>
              <th className={scrollableTableThClassName}>Previous Location</th>
              <th className={scrollableTableThClassName}>New Location</th>
              <th className={scrollableTableThClassName}>Position</th>
              <th className={scrollableTableThClassName}>Shift</th>
              <th className={scrollableTableThClassName}>Generated By</th>
              <th className={scrollableTableThClassName}>Date Generated</th>
            </tr>
          </thead>
          <tbody className={scrollableTableBodyClassName}>
            {filteredHistory.length === 0 ? (
              <tr>
                <td
                  colSpan={11}
                  className="px-4 py-8 text-center text-sm text-slate-500"
                >
                  {initialHistory.length === 0
                    ? "No roster history records yet. Records appear here after a Duty Roster rotation is started."
                    : "No roster history records match the selected filters."}
                </td>
              </tr>
            ) : (
              filteredHistory.map((row, index) => (
                <tr key={row.roster_number} className={getStripedRowClassName(index)}>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.roster_number}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.rotation_number ?? "—"}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.effective_date}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.end_date ?? "—"}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.employee_id
                      ? (employeeNameById.get(row.employee_id) ?? row.employee_id)
                      : "—"}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.previous_location ?? "—"}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.new_location ?? "—"}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.position ?? "—"}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.shift ?? "—"}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.generated_by ?? "—"}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-900">
                    {row.date_generated ?? "—"}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </ScrollableTable>
    </div>
  );
}
